// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdqnhdigikbbyvfnmlex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkcW5oZGlnaWtiYnl2Zm5tbGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDYzOTgsImV4cCI6MjA2NDQyMjM5OH0.4BhcQG4YF3SgF-wtlaewS4w9H3eQka3NKZOecBUbjHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);